version: '2'

services:


  myapp:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: producao-app
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/mydatabase
      - SPRING_CLOUD_AWS_CREDENTIALS_ACCESS_KEY=test
      - SPRING_CLOUD_AWS_CREDENTIALS_SECRET_KEY=test
      - SPRING_CLOUD_AWS_REGION_STATIC=us-east-1
      - SPRING_CLOUD_AWS_SQS_ENDPOINT=http://localstack:4566
      - SERVER_PORT=8080
      - DOCKER_HOST=unix:///var/run/docker.sock


    depends_on:
      - mongo
      - localstack
    ports:
        - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - lanchonete-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - lanchonete-network

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    networks:
      - lanchonete-network


networks:
  lanchonete-network:
    driver: bridge