apiVersion: v1
kind: Service
metadata:
  name: lanchonete-service
spec:
  type: LoadBalancer
  selector:
    app: lanchonete
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

